:green_heart: Check version before release action (#46)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,6 +8,7 @@ on:
       - main
     paths:
       - pyproject.toml
+      - .github/workflows/release.yml
   workflow_dispatch:
 
 env:
@@ -15,17 +16,68 @@ env:
   PYTHON_VERSION: "3.11"
   WORKING_DIRECTORY: "promptogen"
   RELEASE_BRANCH: "main"
-  RELEASE_LABEL: "release"
 
 jobs:
-  if_release:
-    if: |
-        ${{ github.event.pull_request.merged == true }}
-        && ${{ contains(github.event.pull_request.labels.*.name, env.RELEASE_LABEL) }}
+  check_version:
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ${{ inputs.working-directory }}
+    outputs:
+      changed: ${{ steps.compare.outputs.changed }}
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 100
+        sparse-checkout: |
+          scripts/extract_version_by_commit.sh
+          pyproject.toml
+
+    - name: Ensure script exists
+      run: |
+        if [[ ! -f ./scripts/extract_version_by_commit.sh ]]; then
+          echo "Error: extract_version_by_commit.sh script not found!"
+          exit 1
+        fi
+
+    - name: Get Old Version
+      id: old_version
+      run: |
+        version=$(./scripts/extract_version_by_commit.sh ${{ github.event.before }} pyproject.toml)
+        if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Error: Invalid old version format: $version"
+          exit 1
+        fi
+        echo "version=$version" >> $GITHUB_OUTPUT
+
+    - name: Get New Version
+      id: new_version
+      run: |
+        version=$(./scripts/extract_version_by_commit.sh ${{ github.sha }} pyproject.toml)
+        if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Error: Invalid new version format: $version"
+          exit 1
+        fi
+        echo "version=$version" >> $GITHUB_OUTPUT
+
+    - name: Compare versions
+      id: compare
+      run: |
+        echo "old_version=${{ steps.old_version.outputs.version }}"
+        echo "new_version=${{ steps.new_version.outputs.version }}"
+
+        if [ "${{ steps.old_version.outputs.version }}" != "${{ steps.new_version.outputs.version }}" ]; then
+          echo "changed=true" >> $GITHUB_OUTPUT
+        else
+          echo "changed=false" >> $GITHUB_OUTPUT
+        fi
+        cat $GITHUB_OUTPUT
+
+  if_release:
+    needs: check_version
+    if: |
+        needs.check_version.outputs.changed == 'true'
+        && github.event.pull_request.merged == true
+        && contains(github.event.pull_request.labels.*.name, 'release')
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Set up Python ${{ env.PYTHON_VERSION }}
@@ -56,4 +108,4 @@ jobs:
         env:
           POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
         run: |
-          poetry publish
+          poetry publish --dry-run
